name: Apply Terraform

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  deployment:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      workingdirectory: "terraform"

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.workingdirectory}}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{env.workingdirectory}}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{env.workingdirectory}}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{env.workingdirectory}}