name: Apply Terraform

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  deployment:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      workingdirectory: "terraform"
      ARM_CLIENT_ID: ${{secrets.AZURE_SP_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_SP_SECRET}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SP_SUBSCRIPTION_ID}}
      AZURE_ACTION_GROUP_ID: ${{secrets.AZURE_ACTION_GROUP_ID}}

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - run: |
        find . -name "*.tf" -type f -exec sed -i '' -e 's|__AZURE_ACTION_GROUP_ID__|${{ env.AZURE_ACTION_GROUP_ID }}|g' {} +
        find . -name "*.tf" -type f -exec sed -i '' -e 's|__ARM_CLIENT_ID__|${{ env.ARM_CLIENT_ID }}|g' {} +
        find . -name "*.tf" -type f -exec sed -i '' -e 's|__ARM_CLIENT_SECRET__|${{ env.ARM_CLIENT_SECRET }}|g' {} +
        find . -name "*.tf" -type f -exec sed -i '' -e 's|__ARM_TENANT_ID__|${{ env.ARM_TENANT_ID }}|g' {} +
        find . -name "*.tf" -type f -exec sed -i '' -e 's|__ARM_SUBSCRIPTION_ID__|${{ env.ARM_SUBSCRIPTION_ID }}|g' {} +
      name: Replace text

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.24

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.workingdirectory}}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{env.workingdirectory}}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{env.workingdirectory}}