name: Apply Terraform

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  deployment:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      workingdirectory: "terraform"
      ARM_CLIENT_ID: ${{secrets.AZURE_SP_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_SP_SECRET}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_ACTION_GROUP_ID: ${{secrets.AZURE_ACTION_GROUP_ID}}

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - run:  echo ${{ env.ARM_CLIENT_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.24

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.workingdirectory}}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{env.workingdirectory}}
      with:
        args: '-var="action_group_id=${{ env.AZURE_ACTION_GROUP_ID }}"'

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{env.workingdirectory}}
      with:
        args: '-var="action_group_id=${{ env.AZURE_ACTION_GROUP_ID }}"'